set pytorch seed
INFO:2025-05-11 06:37:25,306: - root - : ogbn-papers100M_0.9997_GAT_node_0.01
INFO:2025-05-11 06:37:25,346: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/processed_data/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:25,346: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/analysis_data/optimal/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:25,346: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/analysis_data/posteriors/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:25,346: - data_zoo - : loading raw data
This will download 56.17GB. Will you proceed? (y/N)
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    LGU(args)
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/large_graph_unlearning_LGU.py", line 90, in __init__
    self.load_data()
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/large_graph_unlearning_LGU.py", line 423, in load_data
    self.data = self.data_zoo.load_raw_data()
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/data_zoo.py", line 186, in load_raw_data
    dataset = PygNodePropPredDataset(root=config.RAW_DATA_PATH, name=self.dataset_name, transform=self.transform)
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/ogb/nodeproppred/dataset_pyg.py", line 68, in __init__
    super(PygNodePropPredDataset, self).__init__(self.root, transform, pre_transform)
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 55, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 91, in __init__
    self._download()
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 185, in _download
    self.download()
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/ogb/nodeproppred/dataset_pyg.py", line 125, in download
    if decide_download(url):
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/ogb/utils/url.py", line 17, in decide_download
    return input("This will download %.2fGB. Will you proceed? (y/N)\n" % (size)).lower() == "y"
EOFError: EOF when reading a line
set pytorch seed
INFO:2025-05-11 06:37:28,363: - root - : ogbn-papers100M_0.9998_GAT_node_0.01
INFO:2025-05-11 06:37:28,405: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/processed_data/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:28,405: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/analysis_data/optimal/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:28,405: - data_zoo - : folder /home/zitong/graph_unlearning/IDEA/IDEA/datasets/analysis_data/posteriors/ogbn-papers100M exists, do not need to create again.
INFO:2025-05-11 06:37:28,405: - data_zoo - : loading raw data
ogbn-papers100M has been updated.
Will you update the dataset now? (y/N)
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    LGU(args)
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/large_graph_unlearning_LGU.py", line 90, in __init__
    self.load_data()
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/large_graph_unlearning_LGU.py", line 423, in load_data
    self.data = self.data_zoo.load_raw_data()
  File "/home/zitong/graph_unlearning/scalable_GNN_unlearning/src/data_zoo.py", line 186, in load_raw_data
    dataset = PygNodePropPredDataset(root=config.RAW_DATA_PATH, name=self.dataset_name, transform=self.transform)
  File "/home/zitong/miniconda3/envs/py38_torch1.10.1_cu111_zitong/lib/python3.8/site-packages/ogb/nodeproppred/dataset_pyg.py", line 55, in __init__
    if input('Will you update the dataset now? (y/N)\n').lower() == 'y':
EOFError: EOF when reading a line
